### ISSUE TITLE
Is this plugin still available?

### ISSUE THREAD

**Issue by krishkal** [Arcticus/Cordova-Plugin---Test-Flight-Detector#2]
$ cordova plugin add com.gosyntactix.cordova.testflightdetector
Error: Not found : com.gosyntactix.cordova.testflightdetector

Am I missing something, or is the plugin not found in the Cordova repo?

**Comment by Arcticus** [comment]
Hi Krishkal, the Cordova plugin repository has made changes since this plugin was written and thus may no longer be listed.  However, the code should still be valid and could be manually added.  Right now there are no plans to update and resubmit into the repository.

**Comment by carys-cc** [comment]
I was able to install the plugin using the following command

`ionic cordova plugin add https://github.com/Arcticus/Cordova-Plugin---Test-Flight-Detector.git
`

Detection of TestFlight seems to be working fine.

**Comment by alexp25** [comment]
@patrickchoi how do you use the plugin?
By using this code it doesn't seem to detect the TestFlight distribution correctly:
```
if (TFDetect.isTFXC) {
	// local debug
	console.log("local");
} else {
	if (TFDetect.isAppStore) {
	  // production
	  console.log("app store");
	} else {
	  // testflight
	  console.log("testflight");
	}
}
```
